# terraform-plan.yml
name: "Terraform Plan"

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: read # Required to check out code
  pull-requests: write # Required to post a PR comment
  security-events: write # Required for SARIF upload

jobs:
  checkov-scan:
    name: "Security Scan (Checkov)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          output_format: sarif
          output_file_path: checkov.sarif
          soft_fail: true

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif

  # --- CORRECTED INFRACOST JOB (USING CLI) ---
  infracost:
    name: "Cost Estimation"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Install Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh

      - name: Run Infracost breakdown
        run: infracost breakdown --path . --format json --out-file infracost.json
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

      # --- THIS STEP IS NOW FIXED ---
      - name: Post Infracost comment
        run: |
          infracost comment github --path infracost.json \
            --behavior update \
            --repo ${{ github.repository }} \
            --pull-request ${{ github.event.pull_request.number }} \
            --github-token ${{ secrets.GITHUB_TOKEN }}
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

  # --- TERRAFORM PLAN JOB ---
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    needs: [checkov-scan, infracost]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan

      - name: Convert plan to text
        run: terraform show -no-color tfplan > tfplan.txt

      - name: Add Plan to PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const { readFileSync } = require('fs');
            const plan = readFileSync('tfplan.txt', 'utf8');

            const output = `#### Terraform Plan 📖 (OIDC)

            \`\`\`terraform
            ${plan}
            \`\`\`

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
