# terraform-plan.yml
name: "Terraform Plan"

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: read # Required to check out code
  pull-requests: write # Required to post a PR comment
  security-events: write # Required for tfsec to post findings

jobs:
  # --- NEW JOB: TFSEC SCAN ---
  tfsec-scan:
    name: "Security Scan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Run the tfsec-pr-commenter action
      # This will scan the code and post findings as PR comments
      - name: Run tfsec
        uses: aquasecurity/tfsec-pr-commenter@v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # --- UPDATED JOB: TERRAFORM PLAN ---
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    needs: tfsec-scan # <-- This is new! It waits for the scan to pass.

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan

      - name: Convert plan to text
        run: terraform show -no-color tfplan > tfplan.txt

      - name: Add Plan to PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const { readFileSync } = require('fs');
            const plan = readFileSync('tfplan.txt', 'utf8');

            const output = `#### Terraform Plan 📖 (OIDC)

            \`\`\`terraform
            ${plan}
            \`\`\`

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
