# terraform-plan.yml
name: "Terraform Plan"

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: read # Required to check out code
  pull-requests: write # Required to post a PR comment
  security-events: write # Required for SARIF upload

jobs:
  checkov-scan:
    name: "Security Scan (Checkov)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          output_format: sarif
          output_file_path: checkov.sarif
          soft_fail: true

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif

  # --- CORRECTED INFRACOST JOB ---
  infracost:
    name: "Cost Estimation"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      # Step 1: Run Infracost breakdown using the correct action
      - name: Run Infracost
        uses: infracost/actions@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          path: .
          format: json
          out-file: infracost.json

      # Step 2: Post the comment using the same action
      - name: Post Infracost Comment
        uses: infracost/actions@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          path: infracost.json
          behavior: update

  # --- TERRAFORM PLAN JOB ---
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    # Wait for BOTH security and cost scans to finish
    needs: [checkov-scan, infracost]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan

      - name: Convert plan to text
        run: terraform show -no-color tfplan > tfplan.txt

      - name: Add Plan to PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const { readFileSync } = require('fs');
            const plan = readFileSync('tfplan.txt', 'utf8');

            const output = `#### Terraform Plan 📖 (OIDC)

            \`\`\`terraform
            ${plan}
            \`\`\`

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
